Starting trial 6 with gamma1=0.1, gamma2=0.5, gamma3=0.1
cuda:7
In env continuous
<module 'config' from '/home/ubuntu/noisy_mujoco/abiomed_env/config.py'>
time series transformer device cuda:7
Using device: cuda:7
/home/ubuntu/miniconda3/envs/mopo/lib/python3.8/site-packages/torch/nn/modules/transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.self_attn.batch_first was not True(use batch_first for better inference performance)
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
/home/ubuntu/noisy_mujoco/abiomed_env/model.py:402: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(path, map_location=self.device)
Model loaded from /abiomed/downsampled/models/10min_1hr_all_data_model.pth
loaded datasets with length
 train:  12051
 val:  1938
 test:  3876
Data loaded from /abiomed/downsampled/10min_1hr_all_data.pkl
Continuous action space. Min action: -2.2312597235306466, Max action: 1.8085589693336617
No validation data for Abiomed dataset
0.1 0.5 0.1
torch.Size([17865, 6, 12]) torch.Size([17865, 6]) torch.Size([17865, 66])
 63%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                     | 11210/17865 [00:05<00:03, 2156.46it/s]
Traceback (most recent call last):
  File "hpo/hpo.py", line 294, in <module>
    results_df, best_params, best_model_path = run_hyperparameter_search(args, gamma_ranges)
  File "hpo/hpo.py", line 140, in run_hyperparameter_search
    policy, custom_metric, metrics, save_path = train(trial_args)
  File "/home/ubuntu/SVR/SVR_old/main.py", line 61, in train
    replay_buffer.convert_abiomed(dataset, env, args.fs)
  File "/home/ubuntu/SVR/utils.py", line 149, in convert_abiomed
    reward = env._compute_reward(next_observation[i].reshape(-1,self.timesteps, self.feature_dim), observation[i].reshape(1,self.timesteps, self.feature_dim), action2)
  File "/home/ubuntu/noisy_mujoco/abiomed_env/rl_env.py", line 137, in _compute_reward
    state_reshaped_unnorm = self.world_model.unnorm_output(state_reshaped)
  File "/home/ubuntu/noisy_mujoco/abiomed_env/model.py", line 635, in unnorm_output
    return output.cpu() * self.std[self.columns] + self.mean[self.columns]
KeyboardInterrupt
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/mopo/lib/python3.8/site-packages/wandb/sdk/lib/service_connection.py", line 94, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "/home/ubuntu/miniconda3/envs/mopo/lib/python3.8/site-packages/wandb/sdk/lib/service_connection.py", line 226, in teardown
    self._router.join()
  File "/home/ubuntu/miniconda3/envs/mopo/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 75, in join
    self._thread.join()
  File "/home/ubuntu/miniconda3/envs/mopo/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/home/ubuntu/miniconda3/envs/mopo/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
